server:
  port: 8080

spring:
  redis:
    port: 6379
    password: 123456
    host: 106.37.72.221
    lettuce:
      pool:
        max-active: 40
        max-idle: 8
        min-idle: 0
        max-wait: 5000

# minio 文件存储配置信息
minio:
  endpoint: http://106.37.72.221:9000
  accessKey: minio
  secretKey: "minio@pass123!"
  bucketName: aivision

logging:
  file:
    path: /tmp/log

task:
  image-queue: iq
  image-result-queue: original_res
  timeout: 20000
  monitor-time: 5000
  push-url: "http://10.99.0.33:19090/aiproject/dynamic/taskData"
  monior-url: "http://10.99.0.33:19090/aiproject/dynamic/taskStatus"
  pull-sleep: 1000
